---
$schemaver: '2.0'
repo_url: https://github.com/byu-oit/byu_swagger_reference
software:
  - name: byu_swagger_reference
    type: library
    aliases:
    short_description: Repository for swagger references they can be dereferenced
        in aws s3 bucket dereference_swagger_byu
    assignment_group: gro:AD-Miscellaneous Information Applications
    notes:
    maintained_by:
      - martingarn
    developed_by_byu: true
    ddd:
        business_domain:
        ubiquitous_language_url:
        context_map_url:
    links:
        system_documentation_url: https://github.com/byu-oit/byu_swagger_reference
        swagger_urls:
    microservice: true
    technologies_used:
      - Shell
    standard_change_template_id:
    stages:
        development:
            urls:
                product_page:
                physical_url:
                virtual_url:
            hosting_location: Other
            aws_account:
            relationships:
                depends_on:
                    db_read_write:
                    db_read_only:
                    software:
                supports:
                    software:
                    service:
                reverse_proxy:
                runs_on:
                    server_cluster:
                    virtual_server:
                    rack_server:
                    blade_server:
    tags:
        data-sensitivity: confidential
        team: gro:AD-Miscellaneous Information Applications
        app: byu_swagger_reference
